services:
  pgdatabase:
    image: "postgres:13"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    ports:
      - "5433:5432"
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:wr"
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes: 
      - ./pgAdmin_data:/var/lib/pgadmin:wr”
    ports:
      - "9081:80"


        


